import { Ticket } from "@/lib/types";

export const tickets: Ticket[] = [
  {
    id: "48213",
    subject: "OAuth token refresh failing intermittently in production",
    status: "solution_provided",
    priority: "high",
    severity: "major",
    product: { id: "platform", name: "Cognite Platform" },
    environment: "Production",
    createdAt: "2026-08-05T14:22:00Z",
    updatedAt: "2026-08-08T09:10:00Z",
    assignedTeam: "Platform Support",
    requester: { name: "Daniel Ortiz", email: "daniel.ortiz@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { nextResponseDueAt: "2026-08-10T14:22:00Z", resolutionDueAt: "2026-08-12T14:22:00Z", atRisk: false, breached: false },
    nextExpectedAction: "Please confirm whether the suggested fix resolved the issue.",
    tags: ["oauth", "authentication", "production"],
    attachments: [{ id: "att1", fileName: "token-refresh-error.log", sizeKb: 84, contentType: "text/plain" }],
    messages: [
      {
        id: "m1",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "We're seeing intermittent 401 errors when our backend tries to refresh OAuth tokens via the /oauth/token endpoint. Started roughly 6 hours ago, affects about 3% of refresh calls. Attached the relevant log excerpt.",
        createdAt: "2026-08-05T14:22:00Z",
        attachments: [{ id: "att1", fileName: "token-refresh-error.log", sizeKb: 84, contentType: "text/plain" }],
      },
      {
        id: "m2",
        author: { name: "Ask AI", role: "ai", avatarInitials: "AI" },
        body: "I looked into similar reports — this matches a known clock-skew issue on refresh tokens issued right before rotation. Escalating to Platform Support with your log attached since this needs backend verification.",
        createdAt: "2026-08-05T14:23:00Z",
      },
      {
        id: "m3",
        author: { name: "Priya Nandakumar", role: "agent", avatarInitials: "PN", team: "Platform Support" },
        body: "Thanks for the detailed log, Daniel. We can confirm a small subset of refresh tokens issued between 08:00–08:40 UTC on Aug 5 had an incorrect `exp` claim due to a deploy on our end. We've rolled back the change. Could you retry the affected refresh flow and let us know if the 401s stop?",
        createdAt: "2026-08-06T11:05:00Z",
      },
      {
        id: "m4",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "Retried this morning — no 401s in the last 4 hours. Looking good so far, will keep monitoring through today.",
        createdAt: "2026-08-07T15:40:00Z",
      },
      {
        id: "m5",
        author: { name: "Priya Nandakumar", role: "agent", avatarInitials: "PN", team: "Platform Support" },
        body: "Great to hear. We've been monitoring on our side too and error rates are back to baseline. Marking this as solved on our end — please confirm below so we can close this out, or let us know if it resurfaces.",
        createdAt: "2026-08-08T09:10:00Z",
      },
    ],
  },
  {
    id: "48190",
    subject: "Unable to export usage report as CSV",
    status: "investigating",
    priority: "normal",
    severity: "minor",
    product: { id: "analytics", name: "Cognite Analytics" },
    environment: "Production",
    createdAt: "2026-08-07T10:02:00Z",
    updatedAt: "2026-08-08T16:44:00Z",
    assignedTeam: "Analytics Support",
    requester: { name: "Daniel Ortiz", email: "daniel.ortiz@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { nextResponseDueAt: "2026-08-10T10:02:00Z", resolutionDueAt: "2026-08-14T10:02:00Z", atRisk: false, breached: false },
    nextExpectedAction: "Our team is reproducing the issue with your account's report configuration.",
    tags: ["analytics", "export"],
    attachments: [],
    messages: [
      {
        id: "m1",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "Clicking 'Export CSV' on the Usage Report page spins forever and never downloads. Tried Chrome and Safari, same result.",
        createdAt: "2026-08-07T10:02:00Z",
      },
      {
        id: "m2",
        author: { name: "Sofia Reyes", role: "agent", avatarInitials: "SR", team: "Analytics Support" },
        body: "Thanks for flagging this — can you tell us roughly how large the date range is on the report you're exporting? We want to check if this is related to large export sizes timing out.",
        createdAt: "2026-08-08T16:44:00Z",
      },
    ],
  },
  {
    id: "48055",
    subject: "Question about SSO group mapping for new subsidiary",
    status: "waiting_on_customer",
    priority: "normal",
    severity: "minor",
    product: { id: "platform", name: "Cognite Platform" },
    environment: "Production",
    createdAt: "2026-08-01T09:15:00Z",
    updatedAt: "2026-08-06T13:20:00Z",
    assignedTeam: "Identity & Access",
    requester: { name: "Priya Sharma", email: "priya.sharma@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { nextResponseDueAt: undefined, resolutionDueAt: "2026-08-15T09:15:00Z", atRisk: false, breached: false },
    nextExpectedAction: "We're waiting on your team to confirm the target group names in your IdP.",
    tags: ["sso", "saml", "identity"],
    attachments: [],
    messages: [
      {
        id: "m1",
        author: { name: "Priya Sharma", role: "customer", avatarInitials: "PS" },
        body: "We just onboarded a subsidiary and need their Okta groups mapped to the right Cognite roles. What's the process for adding new group mappings to our existing SAML config?",
        createdAt: "2026-08-01T09:15:00Z",
      },
      {
        id: "m2",
        author: { name: "Marcus Webb", role: "agent", avatarInitials: "MW", team: "Identity & Access" },
        body: "Happy to help — could you share the exact Okta group names you'd like mapped, and which Cognite roles (Admin / Member / Viewer) each should map to? Once we have that we can update your SAML attribute mapping.",
        createdAt: "2026-08-06T13:20:00Z",
      },
    ],
  },
  {
    id: "47998",
    subject: "Dashboard widgets not loading after last release",
    status: "resolved",
    priority: "high",
    severity: "major",
    product: { id: "analytics", name: "Cognite Analytics" },
    environment: "Production",
    createdAt: "2026-07-28T08:30:00Z",
    updatedAt: "2026-07-30T17:00:00Z",
    assignedTeam: "Analytics Support",
    requester: { name: "Daniel Ortiz", email: "daniel.ortiz@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { atRisk: false, breached: false },
    nextExpectedAction: "No action needed — this ticket is resolved.",
    tags: ["dashboard", "regression"],
    csatSubmitted: true,
    attachments: [],
    recap: {
      whatHappened: "After a platform release, all dashboard widgets failed to load and showed an infinite loading spinner instead of data.",
      whyItHappened: "A regression in the widget data-fetch layer was introduced by that day's deploy — an API response shape change wasn't handled by the older widget client still cached in some browsers.",
      whatFixedIt: "The team rolled back the deploy immediately. Widgets returned to normal within minutes, with no data loss — a page refresh was all customers needed once the rollback completed.",
    },
    messages: [
      {
        id: "m1",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "After today's release, none of our dashboard widgets load — just an infinite spinner.",
        createdAt: "2026-07-28T08:30:00Z",
      },
      {
        id: "m2",
        author: { name: "Sofia Reyes", role: "agent", avatarInitials: "SR", team: "Analytics Support" },
        body: "Confirmed a regression in the widget data-fetch layer from today's deploy, already rolled back. You should see widgets loading normally now — can you confirm?",
        createdAt: "2026-07-28T12:10:00Z",
      },
      {
        id: "m3",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "Confirmed fixed, thanks for the quick turnaround.",
        createdAt: "2026-07-30T17:00:00Z",
      },
    ],
  },
  {
    id: "47820",
    subject: "Feature request: bulk user deactivation",
    status: "closed",
    priority: "low",
    severity: "minor",
    product: { id: "platform", name: "Cognite Platform" },
    createdAt: "2026-07-15T11:00:00Z",
    updatedAt: "2026-07-18T09:00:00Z",
    assignedTeam: "Platform Support",
    requester: { name: "Priya Sharma", email: "priya.sharma@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { atRisk: false, breached: false },
    nextExpectedAction: "No action needed — this ticket is closed.",
    tags: ["feature-request"],
    attachments: [],
    messages: [
      {
        id: "m1",
        author: { name: "Priya Sharma", role: "customer", avatarInitials: "PS" },
        body: "Would love a way to deactivate multiple users at once instead of one at a time.",
        createdAt: "2026-07-15T11:00:00Z",
      },
      {
        id: "m2",
        author: { name: "Marcus Webb", role: "agent", avatarInitials: "MW", team: "Platform Support" },
        body: "Thanks for the suggestion — logged with our product team as a feature request. Closing this ticket, but you can track the request status in our release notes.",
        createdAt: "2026-07-18T09:00:00Z",
      },
    ],
  },
  {
    id: "48240",
    subject: "API rate limit hit during nightly sync job",
    status: "submitted",
    priority: "urgent",
    severity: "critical",
    product: { id: "platform", name: "Cognite Platform" },
    environment: "Production",
    createdAt: "2026-08-09T06:12:00Z",
    updatedAt: "2026-08-09T06:12:00Z",
    assignedTeam: "Platform Support",
    requester: { name: "Daniel Ortiz", email: "daniel.ortiz@acmecorp.com" },
    organization: "Acme Corporation",
    sla: { nextResponseDueAt: "2026-08-09T08:12:00Z", resolutionDueAt: "2026-08-09T18:12:00Z", atRisk: true, breached: false },
    nextExpectedAction: "Our team has been notified and will respond shortly given the urgent priority.",
    tags: ["api", "rate-limit"],
    attachments: [{ id: "att2", fileName: "sync-job-trace.json", sizeKb: 212, contentType: "application/json" }],
    messages: [
      {
        id: "m1",
        author: { name: "Daniel Ortiz", role: "customer", avatarInitials: "DO" },
        body: "Our nightly sync job started failing at 06:00 UTC with 429 Too Many Requests, even though we haven't changed our call volume. This is blocking our downstream reporting pipeline — need help urgently.",
        createdAt: "2026-08-09T06:12:00Z",
        attachments: [{ id: "att2", fileName: "sync-job-trace.json", sizeKb: 212, contentType: "application/json" }],
      },
    ],
  },
];

export function getTicketById(id: string): Ticket | undefined {
  return tickets.find((t) => t.id === id);
}

export function getTicketCountsByStatus() {
  const counts: Record<string, number> = {};
  for (const t of tickets) counts[t.status] = (counts[t.status] ?? 0) + 1;
  return counts;
}
